FROM python:3


# set working directory
#RUN mkdir -p /usr/src
WORKDIR /usr/src
# -- copy project -> currently sharing via docker-compose
# COPY . /usr/src

# add requirements (to leverage Docker cache)
ADD ./requirements.workers.txt /usr/src/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# -- Spawn workers according to config
# -- Currently this is taken care of by/in docker-compose.yml
# ENTRYPOINT ["/bin/bash", "-c", "supervisord -c /usr/src/workers/supervisord.conf -n"]
