

STATUS_STARTING = 'STARTING'
STATUS_SUCCEEDED = 'SUCCEEDED'
STATUS_FAILED = 'FAILED'
STATUS_QUEUED = 'QUEUED'
STATUS_RUNNING = 'RUNNING'
STATUS_FINISHED_WITH_ERRORS = 'FINISHED_WITH_ERRORS'


STATUS_CODES = [STATUS_STARTING, STATUS_SUCCEEDED, STATUS_FAILED, STATUS_QUEUED, STATUS_RUNNING, STATUS_FINISHED_WITH_ERRORS]